Feature/#36 header adder클래스생성 및 default method executor 보완
izone00/webserv pull request #38
Opened 2023-08-05 18:25 UTC by spew11

이슈사항 구현했어욧!! 
소영님 ResponseBuilder 대강 어떤 느낌으로 쓰는지 적어놓고 갑니당. 곧 자세해져서 컴백할께요
``` c++
string request = "GET /bin/ HTTP/1.1\r\n";
	HttpResponseBuilder rhb; //빌더 생성
	rhb.initiate(request, WebservValues, locationMap); //초기화
	string host = rhb.getRequestMessage().getHeader("host") //host 확인하는 것
	while (rhb.getNeedCgiFlag != false) {
		rhb.addRequestMessage(std::string) //스트링 타입 계속 넣기
	}
	/* Cgi 쓸지 말지 무슨 스크립터 쓸지 판단하는 클래스 아직 안짬..영원히 안짤수도,,그냥 분기문쓸지도..
	if (hrb.getNeedCgiFlag == true) {
		어쩌고 저쩌고..
	}*/
	MethodExecutor methodExecutor = new CgiMethodExcutor(); // 요런 느낌으로 생성
	hrb.build(methodExecutor);
	string response = hrb.getResponseMessage().toString();

```

2023-08-06 03:39 UTC, ssoyeong-lee approved these changes

2023-08-06 05:37 UTC, izone00 approved these changes

2023-08-06 07:51 UTC, ssoyeong-lee requested changes

2023-08-06 07:51 UTC, ssoyeong-lee commented on include/CgiMethodExecutor.hpp
>          int postMethod(const string &pathToSave, const string &content) const;
1. getMethod, postMethod 함수 내에서, content 변경 시도시 에러 발생 -> 함수 뒤 const 삭제해야 할 듯...
2. cgi에서 post는 request의 body를 이용해 스크립트 실행 -> request body 어디서 가져오지...?

2023-08-06 16:17 UTC, spew11 commented on include/CgiMethodExecutor.hpp
>          int postMethod(const string &pathToSave, const string &content) const;
1. const 삭제할껭!!
2. postMethod의 content 매개변수로 전달되는게 사실 request body였는데 내가 매개변수 이름을 이상하게 지은것같다!! 이름 수정할께!,그리고 CGI로 생성된 파일 원래는 stdout으로 출력되겠지만 그거 그냥 postMethod()의 매개변수 std::string &reponse 이런거 추가해서 생성파일 reponse에 저장해주면 좋을 듯해! 이렇게 수정할깝숑 만나서 터킹어바웃해보자ㅎㅎ

2023-08-07 06:54 UTC, ssoyeong-lee approved these changes

2023-08-07 06:59 UTC, merged